import type { RobotSpec } from "./types";
export type { RobotSpec };

export const ROBOT_ROSTER: RobotSpec[] = [
  {
    id: "tombstone",
    name: "TOMBSTONE JR.",
    realInspiration: "Tombstone — Team Seems Reasonable",
    description:
      "Full-body horizontal bar spinner. The most feared weapon in robot combat. Devastating single hits but vulnerable armor.",
    drivingStyle: "aggressive",
    weaponType: "horizontal_spinner",
    weaponDescription: "48\" hardened AR500 steel bar @ 12,000 RPM",
    armorQuality: "standard",
    driveQuality: "standard",
    weaponQuality: "titanium",
    maxSpeed: 175,
    turnRate: 2.1,
    maxWeaponRPM: 12000,
    weaponSpinupRate: 2200,
    weaponKE: 105,
    mass: 12,
    bodyWidth: 70,
    bodyLength: 50,
    primaryColor: "#1c1c1c",
    accentColor: "#aaaaaa",
    trimColor: "#555555",
  },
  {
    id: "riptide",
    name: "RIPTIDE",
    realInspiration: "Riptide — Team Riptide",
    description:
      "Ferociously aggressive horizontal bar spinner. Superb drive team. Known for explosive hits and dramatic arena-shaking collisions.",
    drivingStyle: "aggressive",
    weaponType: "horizontal_spinner",
    weaponDescription: "Hardened steel bar @ 11,000 RPM. Spins up fast.",
    armorQuality: "budget",
    driveQuality: "premium",
    weaponQuality: "premium",
    maxSpeed: 225,
    turnRate: 2.9,
    maxWeaponRPM: 11000,
    weaponSpinupRate: 3800,
    weaponKE: 92,
    mass: 12,
    bodyWidth: 60,
    bodyLength: 44,
    primaryColor: "#0d47a1",
    accentColor: "#42a5f5",
    trimColor: "#1565c0",
  },
  {
    id: "minotaur",
    name: "MINOTAUR",
    realInspiration: "Minotaur — Team Riobotz (Brazil)",
    description:
      "High-speed drum spinner with exceptional driving from Team Riobotz. Rapid repeated impacts tear apart opponents.",
    drivingStyle: "aggressive",
    weaponType: "drum",
    weaponDescription: "Steel drum @ 8,500 RPM. Rapid multi-hit impacts.",
    armorQuality: "premium",
    driveQuality: "titanium",
    weaponQuality: "premium",
    maxSpeed: 245,
    turnRate: 3.3,
    maxWeaponRPM: 8500,
    weaponSpinupRate: 4500,
    weaponKE: 72,
    mass: 12,
    bodyWidth: 54,
    bodyLength: 50,
    primaryColor: "#b71c1c",
    accentColor: "#ff5252",
    trimColor: "#7f0000",
  },
  {
    id: "hydra",
    name: "HYDRA",
    realInspiration: "Hydra — Team Whyachi",
    description:
      "Hydraulic flipper with titanium armor and world-class drive. Wins by controlling opponents and launching them into walls.",
    drivingStyle: "control",
    weaponType: "lifter",
    weaponDescription: "Hydraulic flipper arm. Launches opponents into walls.",
    armorQuality: "titanium",
    driveQuality: "titanium",
    weaponQuality: "standard",
    maxSpeed: 205,
    turnRate: 3.0,
    maxWeaponRPM: 0,
    weaponSpinupRate: 0,
    weaponKE: 18,
    mass: 12,
    bodyWidth: 72,
    bodyLength: 54,
    primaryColor: "#4a148c",
    accentColor: "#ce93d8",
    trimColor: "#7b1fa2",
  },
  {
    id: "witch_doctor",
    name: "WITCH DOCTOR",
    realInspiration: "Witch Doctor — Shenanigans Engineering",
    description:
      "Dual vertical disc spinners with a skull-painted wedge. Reliable, aggressive, and effective against almost any opponent.",
    drivingStyle: "aggressive",
    weaponType: "vertical_spinner",
    weaponDescription: "Dual steel discs @ 7,200 RPM. Launches opponents vertically.",
    armorQuality: "standard",
    driveQuality: "premium",
    weaponQuality: "premium",
    maxSpeed: 200,
    turnRate: 2.7,
    maxWeaponRPM: 7200,
    weaponSpinupRate: 3200,
    weaponKE: 80,
    mass: 12,
    bodyWidth: 58,
    bodyLength: 48,
    primaryColor: "#1b5e20",
    accentColor: "#69f0ae",
    trimColor: "#2e7d32",
  },
  {
    id: "beta",
    name: "BETA",
    realInspiration: "Beta — Team Hurtz / Robo Challenge (UK)",
    description:
      "Pneumatic hammer with hardox steel armor. Designed to out-survive spinners. Wins by attrition — taking hits and dishing them back.",
    drivingStyle: "control",
    weaponType: "hammer",
    weaponDescription: "Pneumatic hammer @ 300ms strike. Piercing on armor gaps.",
    armorQuality: "titanium",
    driveQuality: "standard",
    weaponQuality: "standard",
    maxSpeed: 165,
    turnRate: 2.0,
    maxWeaponRPM: 0,
    weaponSpinupRate: 0,
    weaponKE: 52,
    mass: 12,
    bodyWidth: 66,
    bodyLength: 56,
    primaryColor: "#37474f",
    accentColor: "#90a4ae",
    trimColor: "#546e7a",
  },
  {
    id: "whiplash",
    name: "WHIPLASH",
    realInspiration: "Whiplash — Matt Vasquez",
    description:
      "Lifting forks + vertical disc. The fastest drive in the game. Opportunistic fighter — gets under opponents then hammers them with the disc.",
    drivingStyle: "opportunistic",
    weaponType: "vertical_spinner",
    weaponDescription: "Vertical disc @ 9,000 RPM on rear. Forks lift and position.",
    armorQuality: "standard",
    driveQuality: "titanium",
    weaponQuality: "premium",
    maxSpeed: 255,
    turnRate: 3.6,
    maxWeaponRPM: 9000,
    weaponSpinupRate: 5000,
    weaponKE: 87,
    mass: 12,
    bodyWidth: 52,
    bodyLength: 58,
    primaryColor: "#e65100",
    accentColor: "#ffb300",
    trimColor: "#bf360c",
  },
  {
    id: "shatter",
    name: "SHATTER!",
    realInspiration: "Shatter! — Adam Wrigley",
    description:
      "Electric axe with AR500 head. Precise, methodical control driver. Titanium-quality weapon system with AP rounds — it finds gaps in armor.",
    drivingStyle: "control",
    weaponType: "hammer",
    weaponDescription: "Electric axe @ 200ms strike. AR500 hardened head, AP capable.",
    armorQuality: "premium",
    driveQuality: "premium",
    weaponQuality: "titanium",
    maxSpeed: 195,
    turnRate: 2.8,
    maxWeaponRPM: 0,
    weaponSpinupRate: 0,
    weaponKE: 62,
    mass: 12,
    bodyWidth: 58,
    bodyLength: 52,
    primaryColor: "#212121",
    accentColor: "#f44336",
    trimColor: "#424242",
  },
];

export function getRobotById(id: string): RobotSpec | undefined {
  return ROBOT_ROSTER.find((r) => r.id === id);
}
